name: CI/CD Action

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn

    - name: Test
      run: |
        yarn lint
        
    - name: Build
      run: |
        yarn build
      if: github.ref == 'refs/heads/master'

    - name: Deploy
      run: |
        yarn deploy --if-present
      if: github.ref == 'refs/heads/master'

    - name: Discord notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'UA Parser Extension has been deployed successfully.'
      if: github.ref == 'refs/heads/master'
